Repository IgniteUI/indigo-design-docfx, pull requests merged in 2018-07, with the labels that each got.

#129 Updated Secondary Nav links and added global var for indigo product t…
  en/global.json
  en/toc.yml
  jp/global.json
  jp/toc.yml
Labels: status: awaiting-test

#139 Fixed broken build
  package-lock.json
Labels: status: verified

#156 added overview header
  en/sidebar-toc/toc.yml
Labels: status: verified

#160 fixing build
  en/sidebar-toc/toc.yml
Labels: status: awaiting-test

#195 Update ignite ui docfx template to 1.0.13-beta.1
  package-lock.json
  package.json
Labels: status: in-test
