Repository IgniteUI/indigo-design-docfx, pull requests merged in 2018-08, with the labels that each got.

#205 updated overview video
  en/video-tutorials.md
Labels: status: awaiting-test

#206 Fixed #200.
  jp/components/grid.md
Labels: enhancement

#211 Updated igniteui-docfx-template to version 1.0.13
  package-lock.json
  package.json
Labels: status: verified
