Repository IgniteUI/indigo-design-docfx, pull requests merged in 2020-12, with the labels that each got.

#329 Update template version
  package-lock.json
  package.json
Labels: status: verified

#330 Generate sitemap
  en/api/.gitignore
  en/api/index.md
  en/docfx.json
  jp/api/.gitignore
  jp/api/index.md
  jp/docfx.json
Labels: status: verified

#331 Remove html from sitemap
  gulpfile.js
  package-lock.json
  package.json
Labels: status: verified

#343 Updating getting started Indigo.Design System section
  en/getting-started.md
Labels: status: verified

#372 Overview topics for styling, components, patterns
  en/components/components-overview.md
  en/components/components.md
  en/images/components-page.png
  en/images/patterns_overview.png
  en/images/theme_overview_dark.png
  en/images/theme_overview_default.png
  en/images/theme_overview_vibrant.png
  en/patterns/patterns-overview.md
  en/sidebar-toc/toc.yml
  en/style/styling-overview.md
  jp/images/components-page.png
  jp/images/patterns_overview.png
  jp/images/theme_overview_dark.png
  jp/images/theme_overview_default.png
  jp/images/theme_overview_vibrant.png
Labels: status: verified

#378 Remove no longer valid information from under the "Code Generation" s…
  en/codegen/after-codegen.md
  en/codegen/data-binding.md
  en/codegen/layout-codegen.md
  en/codegen/vscode-plugin.md
  en/sidebar-toc/toc.yml
Labels: localization-pending

#381 Update VSCode Code Generator Topic Screenshots
  en/images/chrome.png
  en/images/step1.gif
  en/images/step2.gif
  en/images/vs-code-extension-drop-down.png
  en/images/vs-code-generator-installed.png
  en/images/vs-code-install-vsix.png
  en/images/vs-code-select-vsix.png
  jp/images/chrome.png
  jp/images/step1.gif
  jp/images/step2.gif
  jp/images/vs-code-extension-drop-down.png
  jp/images/vs-code-generator-installed.png
  jp/images/vs-code-install-vsix.png
  jp/images/vs-code-select-vsix.png
Labels: status: verified

#371 Updated creating your first artboard Indigo.Design System section
  en/creating-an-artboard.md
  en/images/Creating_An_Artboard_2.png
  en/images/Creating_An_Artboard_2@2x.png
  en/images/getting-started-artboard.png
  en/images/getting-started-artboard@2x.png
  en/images/getting-started3.png
  en/images/getting-started3@2x.png
  en/images/getting-started4.png
  en/images/getting-started4@2x.png
  en/images/getting-started5.png
  en/images/getting-started5@2x.png
  en/images/getting-started6.png
  en/images/getting-started6@2x.png
  en/images/getting-started7.png
  en/images/getting-started7@2x.png
  jp/images/Creating_An_Artboard_2.png
  jp/images/Creating_An_Artboard_2@2x.png
  jp/images/getting-started-artboard.png
  jp/images/getting-started-artboard@2x.png
  jp/images/getting-started3.png
  jp/images/getting-started3@2x.png
  jp/images/getting-started4.png
  jp/images/getting-started4@2x.png
  jp/images/getting-started5.png
  jp/images/getting-started5@2x.png
  jp/images/getting-started6.png
  jp/images/getting-started6@2x.png
  jp/images/getting-started7.png
  jp/images/getting-started7@2x.png
Labels: status: verified

#389 Update template to 2.9.3 and remove srcset warnings (vNext)
  en/appbuilder/getting-started.md
  en/images/App-VSCode-Indigo-Design-App-Builder@2x.png
  en/images/Preview-App-Indigo-Design-App-Builder@2x.png
  package-lock.json
  package.json
Labels: status: verified

#396 Fixing errors and update templ to 2.9.4
  gulpfile.js
  package-lock.json
  package.json
Labels: status: verified

#399 [JP] App Builder topic localization. Content update of styling topics.
  jp/appbuilder/app-builder-overview.md
  jp/appbuilder/app-themes/app-themes.md
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/appbuilder/flex-layouts/row-and-column-layout.md
  jp/appbuilder/getting-started.md
  jp/appbuilder/indigo-design-app-builder-components.md
  jp/appbuilder/interface-overview.md
  jp/appbuilder/preview-code-and-generate-app.md
  jp/appbuilder/single-page-apps-and-navigation.md
  jp/codegen/after-codegen.md
  jp/codegen/data-binding.md
  jp/codegen/layout-codegen.md
  jp/components/components-overview.md
  jp/components/grid-export.md
  jp/getting-started.md
  jp/patterns/patterns-overview.md
  jp/sidebar-toc/toc.yml
  jp/style/colors.md
  jp/style/elevation.md
  jp/style/illustrations.md
  jp/style/material-icons.md
  jp/style/styling-overview.md
  jp/style/typography.md
Labels: localized, status: verified

#404 Localization and link fixes
  en/components/components-overview.md
  en/patterns/patterns-overview.md
  jp/appbuilder/app-builder-overview.md
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/appbuilder/indigo-design-app-builder-components.md
  jp/appbuilder/interface-overview.md
  jp/appbuilder/single-page-apps-and-navigation.md
  jp/components/components-overview.md
  jp/patterns/patterns-overview.md
Labels: status: verified
