Repository IgniteUI/indigo-design-docfx, pull requests merged in 2020-02, with the labels that each got.

#301 Fixing bookmark/link issues in JP.
  jp/components/grid.md
  jp/known-issues.md
Labels: localized, status: verified

#304 Renaming images
  en/images/chip_focus_selected_removable.png
  en/images/chip_focus_selected_removable@2x.png
  jp/images/chip_focus_selected_removable.png
  jp/images/chip_focus_selected_removable@2x.png
Labels: status: verified

#306 Fix broken link
  en/components/grid.md
  jp/components/grid.md
Labels: status: verified

#308 Fixed vulnerabilities reported by github
  package-lock.json
  package.json
Labels: status: verified

#309 Update gulp to version 4
  gulpfile.js
  package-lock.json
  package.json
Labels: status: awaiting-test
