Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-07, with the labels that each got.

#513 Update template version -vnext
  package-lock.json
  package.json
Labels: status: verified

#519 Sivanov getting started update
  en/creating-an-artboard.md
Labels: status: verified

#521 [JP] Updating Known Issues and Typography - master
  jp/known-issues.md
  jp/style/typography.md
Labels: localized, status: verified

#522 [JA] Getting started update
  jp/creating-an-artboard.md
Labels: localized, status: verified

#511 Getting started changes
  en/appbuilder/change-log.md
  en/appbuilder/generate-app/generate-app-overview.md
  en/appbuilder/generate-app/run-application-locally.md
  en/appbuilder/generate-app/upload-application-to-github.md
  en/appbuilder/getting-started.md
  en/appbuilder/preview-code-and-genrate-app/compile-and-run-the-app.md
  en/appbuilder/preview-code-and-genrate-app/preview-code.md
  en/appbuilder/preview-code.md
  en/images/connect-to-github-@2x.png
  en/images/connect-to-github.png
  en/images/create-new-repo-publish-to-github-@2x.png
  en/images/create-new-repo-publish-to-github.png
  en/images/indigo-design-resources.gif
  en/images/pick-repository-publish-to-github-@2x.png
  en/images/pick-repository-publish-to-github.png
  en/images/view-application-publish-to-github-@2x.png
  en/images/view-application-publish-to-github.png
  en/sidebar-toc/toc.yml
  en/sync-themes-plugin.md
Labels: priority: medium

#523 Merging vNext into master
  en/appbuilder/change-log.md
  en/appbuilder/generate-app/generate-app-overview.md
  en/appbuilder/generate-app/run-application-locally.md
  en/appbuilder/generate-app/upload-application-to-github.md
  en/appbuilder/getting-started.md
  en/appbuilder/preview-code-and-genrate-app/compile-and-run-the-app.md
  en/appbuilder/preview-code-and-genrate-app/preview-code.md
  en/appbuilder/preview-code.md
  en/creating-an-artboard.md
  en/images/connect-to-github-@2x.png
  en/images/connect-to-github.png
  en/images/create-new-repo-publish-to-github-@2x.png
  en/images/create-new-repo-publish-to-github.png
  en/images/indigo-design-resources.gif
  en/images/pick-repository-publish-to-github-@2x.png
  en/images/pick-repository-publish-to-github.png
  en/images/view-application-publish-to-github-@2x.png
  en/images/view-application-publish-to-github.png
  en/index.md
  en/sidebar-toc/toc.yml
  en/sync-themes-plugin.md
  jp/creating-an-artboard.md
  jp/index.md
  package-lock.json
  package.json
Labels: do not merge

#525 [JA][vNext] Adding the latest changes.
  jp/appbuilder/change-log.md
  jp/appbuilder/generate-app/generate-app-overview.md
  jp/appbuilder/generate-app/run-application-locally.md
  jp/appbuilder/generate-app/upload-application-to-github.md
  jp/appbuilder/getting-started.md
  jp/appbuilder/preview-code-and-generate-app.md
  jp/appbuilder/preview-code-and-genrate-app/compile-and-run-the-app.md
  jp/appbuilder/preview-code-and-genrate-app/preview-code.md
  jp/appbuilder/preview-code.md
  jp/images/Indigo-Design-home-screen.gif
  jp/images/Indigo-Design-side-menu-@2x.png
  jp/images/Indigo-Design-side-menu.png
  jp/images/connect-to-github-@2x.png
  jp/images/connect-to-github.png
  jp/images/create-new-repo-publish-to-github-@2x.png
  jp/images/create-new-repo-publish-to-github.png
  jp/images/indigo-design-resources.gif
  jp/images/pick-repository-publish-to-github-@2x.png
  jp/images/pick-repository-publish-to-github.png
  jp/images/view-application-publish-to-github-@2x.png
  jp/images/view-application-publish-to-github.png
  jp/sidebar-toc/toc.yml
  jp/sync-themes-plugin.md
Labels: localized, status: verified

#527 Onboarding topics UI KIts
  en/creating-artboard-adobexd.md
  en/creating-artboard-sketch.md
  en/getting-started.md
  en/images/Creating_An_Artboard_Sketch2.png
  en/images/Creating_An_Artboard_Sketch2@2x.png
  en/images/Creating_An_Artboard_XD1.png
  en/images/Creating_An_Artboard_XD1@2x.png
  en/images/Creating_An_Artboard_XD2.png
  en/images/Creating_An_Artboard_XD2@2x.png
  en/images/Creating_An_Artboard_XD3.png
  en/images/Creating_An_Artboard_XD3@2x.png
  en/images/getting-started-sketch-artboard.png
  en/images/getting-started-sketch-artboard@2x.png
  en/images/getting-started-sketch0.png
  en/images/getting-started-sketch0@2x.png
  en/images/getting-started-sketch1.png
  en/images/getting-started-sketch1@2x.png
  en/images/getting-started-sketch2.png
  en/images/getting-started-sketch2@2x.png
  en/images/getting-started-sketch3.png
  en/images/getting-started-sketch3@2x.png
  en/images/getting-started-sketch4.png
  en/images/getting-started-sketch4@2x.png
  en/images/getting-started-sketch5.png
  en/images/getting-started-sketch5@2x.png
  en/images/getting-started-sketch6.png
  en/images/getting-started-sketch6@2x.png
  en/images/getting-started-sketch7.png
  en/images/getting-started-sketch7@2x.png
  en/images/getting-started-xd-artboard.png
  en/images/getting-started-xd-artboard@2x.png
  en/images/getting-startedxd0.png
  en/images/getting-startedxd0@2x.png
  en/images/getting-startedxd1.png
  en/images/getting-startedxd1@2x.png
  en/images/getting-startedxd2.png
  en/images/getting-startedxd2@2x.png
  en/images/getting-startedxd3.png
  en/images/getting-startedxd3@2x.png
  en/images/getting-startedxd4.png
  en/images/getting-startedxd4@2x.png
  en/images/getting-startedxd5.png
  en/images/getting-startedxd5@2x.png
  en/images/getting-startedxd6.png
  en/images/getting-startedxd6@2x.png
  en/images/getting-startedxd7.png
  en/images/getting-startedxd7@2x.png
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified
