Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-11, with the labels that each got.

#570 Update appbuilder navigation url
  package-lock.json
  package.json
Labels: status: verified

#569 Update template version- master
  package-lock.json
  package.json
Labels: status: verified

#575 Update Appbuilder links
  en/appbuilder/app-builder-overview.md
  en/appbuilder/app-themes/app-themes.md
  en/appbuilder/getting-started.md
  jp/appbuilder/app-builder-overview.md
  jp/appbuilder/app-themes/app-themes.md
  jp/appbuilder/getting-started.md
Labels: status: verified

#573 Update content for Sketch plugin with Create App story
  en/images/create-from-sketch.gif
  en/sync-themes-plugin.md
Labels: status: verified, localization-pending

#578 Update changelog with latest version updates
  en/appbuilder/change-log.md
Labels: localization-pending

#577 Update changelog with latest releases
  en/appbuilder/change-log.md
Labels: localization-pending

#579 [JA] Updating changelog - vnext
  jp/appbuilder/change-log.md
Labels: status: verified, localized

#580 [JA] Updating changelog and sync-themes-plugin
  jp/appbuilder/change-log.md
  jp/images/create-from-sketch.gif
  jp/images/indigo-design-resources.gif
  jp/sync-themes-plugin.md
Labels: status: verified, localized

#582 Sivanov xd library set up updates
  en/creating-artboard-adobexd.md
  en/images/Creating_An_Artboard_XD.png
  en/images/Creating_An_Artboard_XD2.png
  en/images/Creating_An_Artboard_XD2@2x.png
  en/images/Creating_An_Artboard_XD3.png
  en/images/Creating_An_Artboard_XD3@2x.png
  en/images/Creating_An_Artboard_XD@2x.png
  jp/creating-artboard-adobexd.md
  jp/images/Creating_An_Artboard_XD.png
  jp/images/Creating_An_Artboard_XD2.png
  jp/images/Creating_An_Artboard_XD2@2x.png
  jp/images/Creating_An_Artboard_XD3.png
  jp/images/Creating_An_Artboard_XD3@2x.png
  jp/images/Creating_An_Artboard_XD@2x.png
Labels: status: verified, localized

#584 Remove appbuilder topics -master
  en/appbuilder/app-builder-overview.md
  en/appbuilder/app-themes/app-themes.md
  en/appbuilder/app-themes/customize-and-apply-theme.md
  en/appbuilder/app-themes/material-vs-fluent-vs-bootstrap.md
  en/appbuilder/app-themes/switching-app-themes.md
  en/appbuilder/change-log.md
  en/appbuilder/flex-layouts/add-to-layout-via-context-menu.md
  en/appbuilder/flex-layouts/additional-resources-to-learn-about-web-layouts.md
  en/appbuilder/flex-layouts/flex-layouts.md
  en/appbuilder/flex-layouts/fluid-resizing-and-wrapping.md
  en/appbuilder/flex-layouts/row-and-column-layout.md
  en/appbuilder/generate-app/generate-app-overview.md
  en/appbuilder/generate-app/run-application-locally.md
  en/appbuilder/generate-app/upload-application-to-github.md
  en/appbuilder/getting-started.md
  en/appbuilder/indigo-design-app-builder-components.md
  en/appbuilder/indigo-design-components/configuring-components.md
  en/appbuilder/indigo-design-components/quick-add-components.md
  en/appbuilder/interactions.md
  en/appbuilder/interface-overview.md
  en/appbuilder/preview-code.md
  en/appbuilder/single-page-apps-and-navigation.md
  en/appbuilder/spa-and-navigation/add-navigations-routing.md
  en/appbuilder/spa-and-navigation/master-view-vs-child-views.md
  en/appbuilder/using-data-in-your-app.md
  en/appbuilder/using-data-in-your-app/binding-data-to-components.md
  en/appbuilder/using-data-in-your-app/data-sources.md
  en/global.json
  en/sidebar-toc/toc.yml
  en/video-tutorials.md
  jp/appbuilder/app-builder-overview.md
  jp/appbuilder/app-themes/app-themes.md
  jp/appbuilder/app-themes/customize-and-apply-theme.md
  jp/appbuilder/app-themes/material-vs-fluent-vs-bootstrap.md
  jp/appbuilder/app-themes/switching-app-themes.md
  jp/appbuilder/change-log.md
  jp/appbuilder/flex-layouts/add-to-layout-via-context-menu.md
  jp/appbuilder/flex-layouts/additional-resources-to-learn-about-web-layouts.md
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/appbuilder/flex-layouts/fluid-resizing-and-wrapping.md
  jp/appbuilder/flex-layouts/row-and-column-layout.md
  jp/appbuilder/generate-app/generate-app-overview.md
  jp/appbuilder/getting-started.md
  jp/appbuilder/indigo-design-app-builder-components.md
  jp/appbuilder/indigo-design-components/configuring-components.md
  jp/appbuilder/indigo-design-components/quick-add-components.md
  jp/appbuilder/interactions.md
  jp/appbuilder/interface-overview.md
  jp/appbuilder/preview-code-and-generate-app.md
  jp/appbuilder/preview-code-and-genrate-app/compile-and-run-the-app.md
  jp/appbuilder/preview-code-and-genrate-app/preview-code.md
  jp/appbuilder/preview-code.md
  jp/appbuilder/single-page-apps-and-navigation.md
  jp/appbuilder/spa-and-navigation/add-navigations-routing.md
  jp/appbuilder/spa-and-navigation/master-view-vs-child-views.md
  jp/appbuilder/using-data-in-your-app.md
  jp/global.json
  jp/sidebar-toc/toc.yml
  jp/video-tutorials.md
Labels: status: verified
