Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-02, with the labels that each got.

#450 Updating scheduler pattern topic
  en/images/scheduler.png
  en/images/scheduler@2x.png
  en/images/scheduler_detach.png
  en/images/scheduler_detach@2x.png
  en/patterns/scheduler.md
  jp/images/scheduler.png
  jp/images/scheduler@2x.png
  jp/images/scheduler_detach.png
  jp/images/scheduler_detach@2x.png
Labels: localization-pending, status: verified

#448 Added footer pattern topic
  en/images/footer_desktop_demo.png
  en/images/footer_desktop_demo@2x.png
  en/images/footer_detach.png
  en/images/footer_detach@2x.png
  en/images/footer_mobile_demo.png
  en/images/footer_mobile_demo@2x.png
  en/patterns/footer.md
  en/sidebar-toc/toc.yml
  jp/images/footer_desktop_demo.png
  jp/images/footer_desktop_demo@2x.png
  jp/images/footer_detach.png
  jp/images/footer_detach@2x.png
  jp/images/footer_mobile_demo.png
  jp/images/footer_mobile_demo@2x.png
Labels: localization-pending, status: verified

#451 Adding chat pattern topic
  en/images/chat_desktop_demo.png
  en/images/chat_desktop_demo@2x.png
  en/images/chat_detach.png
  en/images/chat_detach@2x.png
  en/images/chat_mobile_demo.png
  en/images/chat_mobile_demo@2x.png
  en/patterns/chat.md
  en/sidebar-toc/toc.yml
  jp/images/chat_desktop_demo.png
  jp/images/chat_desktop_demo@2x.png
  jp/images/chat_detach.png
  jp/images/chat_detach@2x.png
  jp/images/chat_mobile_demo.png
  jp/images/chat_mobile_demo@2x.png
Labels: localization-pending, status: verified

#453 Adding social feed pattern topic
  en/images/social_feed_articles_demo.png
  en/images/social_feed_articles_demo@2x.png
  en/images/social_feed_detach.png
  en/images/social_feed_detach@2x.png
  en/images/social_feed_mobile_demo.png
  en/images/social_feed_mobile_demo@2x.png
  en/patterns/social-feed.md
  en/sidebar-toc/toc.yml
  jp/images/social_feed_articles_demo.png
  jp/images/social_feed_articles_demo@2x.png
  jp/images/social_feed_detach.png
  jp/images/social_feed_detach@2x.png
  jp/images/social_feed_mobile_demo.png
  jp/images/social_feed_mobile_demo@2x.png
Labels: localization-pending, status: verified

#456 Updating tags on ToC
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified

#446 Form pattern topic update
  en/images/form_address.png
  en/images/form_address@2x.png
  en/images/form_appointment.png
  en/images/form_appointment@2x.png
  en/images/form_booking.png
  en/images/form_booking@2x.png
  en/images/form_card.png
  en/images/form_card@2x.png
  en/images/form_cash.png
  en/images/form_cash@2x.png
  en/images/form_contacts.png
  en/images/form_contacts@2x.png
  en/images/form_demo.png
  en/images/form_demo@2x.png
  en/images/form_detach.png
  en/images/form_detach@2x.png
  en/images/form_donation.png
  en/images/form_donation@2x.png
  en/images/form_email.png
  en/images/form_email@2x.png
  en/images/form_feedback.png
  en/images/form_feedback@2x.png
  en/images/form_free_trial.png
  en/images/form_free_trial@2x.png
  en/images/form_illustrated_account_type.png
  en/images/form_illustrated_account_type@2x.png
  en/images/form_illustrated_card.png
  en/images/form_illustrated_card@2x.png
  en/images/form_illustrated_forgot_password.png
  en/images/form_illustrated_forgot_password@2x.png
  en/images/form_login-horizontal.png
  en/images/form_login-horizontal@2x.png
  en/images/form_login-simple.png
  en/images/form_login-simple@2x.png
  en/images/form_login-social.png
  en/images/form_login-social@2x.png
  en/images/form_money_transfer.png
  en/images/form_money_transfer@2x.png
  en/images/form_new.png
  en/images/form_new@2x.png
  en/images/form_register-horizontal.png
  en/images/form_register-horizontal@2x.png
  en/images/form_register-simple.png
  en/images/form_register-simple@2x.png
  en/images/form_register-social.png
  en/images/form_register-social@2x.png
  en/images/form_search.png
  en/images/form_search@2x.png
  en/images/form_subscription.png
  en/images/form_subscription@2x.png
  en/images/form_transportation_tickets.png
  en/images/form_transportation_tickets@2x.png
  en/patterns/form.md
Labels: localization-pending, status: verified

#457 Created the Dialogs pattern topic and added it to the TOC
  en/images/dialogs_demo.png
  en/images/dialogs_demo@2x.png
  en/images/dialogs_detach.png
  en/images/dialogs_detach@2x.png
  en/patterns/dialogs.md
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified

#459 Empty States pattern topic created
  en/images/empty-states_demo.png
  en/images/empty-states_demo@2x.png
  en/images/empty-states_detach.png
  en/images/empty-states_detach@2x.png
  en/patterns/empty-states.md
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified

#461 Adjusted images in hierarchical grid and scheduler pattern topics
  en/images/hierarchical_grid.png
  en/images/hierarchical_grid@2x.png
  en/images/scheduler.png
  en/images/scheduler@2x.png
  jp/images/hierarchical_grid.png
  jp/images/hierarchical_grid@2x.png
  jp/images/scheduler.png
  jp/images/scheduler@2x.png
Labels: status: verified

#464 [JP] Localization and formatting fixes
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/codegen/layout-codegen.md
  jp/components/card.md
  jp/components/column-chart.md
  jp/components/hierarchical-grid.md
  jp/components/line-chart.md
  jp/components/linear-gauge.md
  jp/components/tree-grid.md
  jp/images/form_appointment.png
  jp/images/form_appointment@2x.png
  jp/images/form_card.png
  jp/images/form_card@2x.png
  jp/images/form_contacts.png
  jp/images/form_contacts@2x.png
  jp/images/form_feedback.png
  jp/images/form_feedback@2x.png
  jp/images/form_free_trial.png
  jp/images/form_free_trial@2x.png
  jp/images/form_illustrated_card.png
  jp/images/form_illustrated_card@2x.png
  jp/images/form_illustrated_forgot_password.png
  jp/images/form_illustrated_forgot_password@2x.png
  jp/images/form_new.png
  jp/images/form_new@2x.png
  jp/images/form_search.png
  jp/images/form_subscription.png
  jp/images/form_subscription@2x.png
  jp/images/form_transportation_tickets.png
  jp/images/form_transportation_tickets@2x.png
  jp/patterns/patterns-overview.md
  jp/style/styling-overview.md
  jp/sync-themes-plugin.md
  jp/video-tutorials.md
Labels: localized, status: verified
