Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-03, with the labels that each got.

#483 updating package.json to fix vulnerabilities - master
  package-lock.json
  package.json
Labels: status: verified

#477 Updating localization - Data Sources topic.
  jp/appbuilder/using-data-in-your-app.md
  jp/images/DataSources - Add JSON file.gif
  jp/images/DataSources - Add URL.gif
  jp/images/DataSources - Change field type.gif
  jp/images/DataSources - Connect data source table fields.gif
  jp/images/DataSources - View data source.gif
  jp/images/dataSources - select fields.gif
  jp/sidebar-toc/toc.yml
Labels: localized, status: verified

#474 docs(vs-code-extension): Change topic to explain installing from marketplace
  en/codegen/installing-vs-code-extension.md
  en/images/vs-code-extension-drop-down.png
  en/images/vs-code-generator-installed.png
  en/images/vs-code-install-vsix.png
  en/images/vs-code-install.png
  en/images/vs-code-select-vsix.png
Labels: localized

#485 VS Code Extention topic localization.
  jp/codegen/installing-vs-code-extension.md
  jp/images/vs-code-generator-installed.png
  jp/images/vs-code-install-vsix.png
  jp/images/vs-code-install.png
  jp/images/vs-code-select-vsix.png
Labels: localized, status: verified

#488 Add indigo cta banner -vnext
  en/images/marketing/indigo-design-cta-banner-2.png
  jp/images/marketing/indigo-design-cta-banner-2.png
Labels: status: awaiting-test

#489 Add indigo cta banner -master
  en/images/marketing/indigo-design-cta-banner-2.png
  jp/images/marketing/indigo-design-cta-banner-2.png
Labels: status: verified

#486 Adding new docfx structure updates -vnext
  en/environment.json
  gulpfile.js
  jp/environment.json
  package-lock.json
  package.json
Labels: status: verified

#493 [JP] Data Sources topic fixes - images - vNext
  jp/appbuilder/using-data-in-your-app.md
  jp/images/DataSources-Add-JSON-file.gif
  jp/images/DataSources-Add-URL.gif
  jp/images/DataSources-Change-field-type.gif
  jp/images/DataSources-Connect-data-source-table-fields.gif
  jp/images/DataSources-View-data-source.gif
  jp/images/dataSources-select-fields.gif
Labels: localized, status: verified
