Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-01, with the labels that each got.

#374 Updated avatar Indigo.Design System section
  en/components/avatar.md
Labels: status: verified

#375 Updated badge Indigo.Design System section
  en/components/badge.md
Labels: status: verified

#376 Updated carousel Indigo.Design System section
  en/components/carousel.md
  en/images/carousel_demo.png
  en/images/carousel_demo@2x.png
  en/images/carousel_indicators&slides.png
  en/images/carousel_indicators&slides@2x.png
  en/images/carousel_styling.png
  en/images/carousel_styling@2x.png
  jp/images/carousel_demo.png
  jp/images/carousel_demo@2x.png
  jp/images/carousel_indicators&slides.png
  jp/images/carousel_indicators&slides@2x.png
  jp/images/carousel_styling.png
  jp/images/carousel_styling@2x.png
Labels: status: verified

#379 Updated checkbox Indigo.Design System section
  en/components/checkbox.md
  en/images/checkbox_interaction_state.png
  en/images/checkbox_interaction_state@2x.png
  en/images/checkbox_label_after.png
  en/images/checkbox_label_after@2x.png
  en/images/checkbox_label_before.png
  en/images/checkbox_label_before@2x.png
  en/images/checkbox_states.png
  en/images/checkbox_states@2x.png
  en/images/checkbox_styling.png
  en/images/checkbox_styling@2x.png
  jp/images/checkbox_interaction_state.png
  jp/images/checkbox_interaction_state@2x.png
  jp/images/checkbox_label_after.png
  jp/images/checkbox_label_after@2x.png
  jp/images/checkbox_label_before.png
  jp/images/checkbox_label_before@2x.png
  jp/images/checkbox_states.png
  jp/images/checkbox_states@2x.png
  jp/images/checkbox_styling.png
  jp/images/checkbox_styling@2x.png
Labels: status: verified

#383 Updating bottom nav topic
  en/components/bottom-nav.md
  en/images/bottom-nav_demo.png
  en/images/bottom-nav_demo@2x.png
  en/images/bottom-nav_do1.png
  en/images/bottom-nav_do1@2x.png
  en/images/bottom-nav_do2.png
  en/images/bottom-nav_do2@2x.png
  en/images/bottom-nav_dont1.png
  en/images/bottom-nav_dont1@2x.png
  en/images/bottom-nav_dont2.png
  en/images/bottom-nav_dont2@2x.png
  en/images/bottom-nav_icon&text.png
  en/images/bottom-nav_icon&text@2x.png
  en/images/bottom-nav_icon.png
  en/images/bottom-nav_icon@2x.png
  en/images/bottom-nav_item_state.png
  en/images/bottom-nav_item_state@2x.png
  en/images/bottom-nav_items2.png
  en/images/bottom-nav_items2@2x.png
  en/images/bottom-nav_items3.png
  en/images/bottom-nav_items3@2x.png
  en/images/bottom-nav_items3_icons.png
  en/images/bottom-nav_items3_icons@2x.png
  en/images/bottom-nav_items4.png
  en/images/bottom-nav_items4@2x.png
  en/images/bottom-nav_items5.png
  en/images/bottom-nav_items5@2x.png
  en/images/bottom-nav_limitation.png
  en/images/bottom-nav_styling.png
  en/images/bottom-nav_styling@2x.png
  jp/images/bottom-nav_demo.png
  jp/images/bottom-nav_demo@2x.png
  jp/images/bottom-nav_do1.png
  jp/images/bottom-nav_do1@2x.png
  jp/images/bottom-nav_do2.png
  jp/images/bottom-nav_do2@2x.png
  jp/images/bottom-nav_dont1.png
  jp/images/bottom-nav_dont1@2x.png
  jp/images/bottom-nav_dont2.png
  jp/images/bottom-nav_dont2@2x.png
  jp/images/bottom-nav_icon&text.png
  jp/images/bottom-nav_icon&text@2x.png
  jp/images/bottom-nav_icon.png
  jp/images/bottom-nav_icon@2x.png
  jp/images/bottom-nav_item_state.png
  jp/images/bottom-nav_item_state@2x.png
  jp/images/bottom-nav_items2.png
  jp/images/bottom-nav_items2@2x.png
  jp/images/bottom-nav_items3.png
  jp/images/bottom-nav_items3@2x.png
  jp/images/bottom-nav_items3_icons.png
  jp/images/bottom-nav_items3_icons@2x.png
  jp/images/bottom-nav_items4.png
  jp/images/bottom-nav_items4@2x.png
  jp/images/bottom-nav_items5.png
  jp/images/bottom-nav_items5@2x.png
  jp/images/bottom-nav_limitation.png
  jp/images/bottom-nav_styling.png
  jp/images/bottom-nav_styling@2x.png
Labels: status: verified

#402 Updated icon topic
  en/components/icon.md
  en/images/icon_demo.png
  en/images/icon_demo@2x.png
  jp/images/icon_demo.png
  jp/images/icon_demo@2x.png
Labels: status: verified

#403 Updating "new" tags on UI Kit components
  en/sidebar-toc/toc.yml
Labels: status: verified

#415 Updated tooltip topic
  en/components/tooltip.md
Labels: status: verified

#412 Updated switch topic
  en/components/switch.md
  en/images/switch_demo.png
  en/images/switch_demo@2x.png
  en/images/switch_do1.png
  en/images/switch_do1@2x.png
  en/images/switch_do2.png
  en/images/switch_do2@2x.png
  en/images/switch_dont1.png
  en/images/switch_dont1@2x.png
  en/images/switch_dont2.png
  en/images/switch_dont2@2x.png
  en/images/switch_enabled&disabled-state.png
  en/images/switch_enabled&disabled-state@2x.png
  en/images/switch_label-after.png
  en/images/switch_label-after@2x.png
  en/images/switch_label-before.png
  en/images/switch_label-before@2x.png
  en/images/switch_no_label.png
  en/images/switch_no_label@2x.png
  jp/images/switch_demo.png
  jp/images/switch_demo@2x.png
  jp/images/switch_do1.png
  jp/images/switch_do1@2x.png
  jp/images/switch_do2.png
  jp/images/switch_do2@2x.png
  jp/images/switch_dont1.png
  jp/images/switch_dont1@2x.png
  jp/images/switch_dont2.png
  jp/images/switch_dont2@2x.png
  jp/images/switch_enabled&disabled-state.png
  jp/images/switch_enabled&disabled-state@2x.png
  jp/images/switch_label-after.png
  jp/images/switch_label-after@2x.png
  jp/images/switch_no_label.png
  jp/images/switch_no_label@2x.png
Labels: status: verified

#411 Updated snackbar topic
  en/components/snackbar.md
  en/images/snackbar_demo.png
  en/images/snackbar_demo@2x.png
  en/images/snackbar_do1.png
  en/images/snackbar_do1@2x.png
  en/images/snackbar_do2.png
  en/images/snackbar_do2@2x.png
  en/images/snackbar_do3.png
  en/images/snackbar_do3@2x.png
  en/images/snackbar_dont1.png
  en/images/snackbar_dont1@2x.png
  en/images/snackbar_dont2.png
  en/images/snackbar_dont2@2x.png
  en/images/snackbar_dont3.png
  en/images/snackbar_dont3@2x.png
  en/images/snackbar_styling.png
  en/images/snackbar_styling@2x.png
  jp/images/snackbar_demo.png
  jp/images/snackbar_demo@2x.png
  jp/images/snackbar_do1.png
  jp/images/snackbar_do1@2x.png
  jp/images/snackbar_do2.png
  jp/images/snackbar_do2@2x.png
  jp/images/snackbar_do3.png
  jp/images/snackbar_do3@2x.png
  jp/images/snackbar_dont1.png
  jp/images/snackbar_dont1@2x.png
  jp/images/snackbar_dont2.png
  jp/images/snackbar_dont2@2x.png
  jp/images/snackbar_dont3.png
  jp/images/snackbar_dont3@2x.png
  jp/images/snackbar_styling.png
  jp/images/snackbar_styling@2x.png
Labels: status: verified

#398 Updated hyperlink topic
  en/components/hyperlink.md
Labels: status: verified

#395 Updated dialog topic
  en/components/dialog.md
  en/images/dialog_alert.png
  en/images/dialog_alert@2x.png
  en/images/dialog_custom.png
  en/images/dialog_custom@2x.png
  en/images/dialog_demo.png
  en/images/dialog_demo@2x.png
  en/images/dialog_do1.png
  en/images/dialog_do1@2x.png
  en/images/dialog_dont1.png
  en/images/dialog_dont1@2x.png
  en/images/dialog_standard.png
  en/images/dialog_standard@2x.png
  en/images/dialog_styling.png
  en/images/dialog_styling@2x.png
  jp/images/dialog_alert.png
  jp/images/dialog_alert@2x.png
  jp/images/dialog_custom.png
  jp/images/dialog_custom@2x.png
  jp/images/dialog_demo.png
  jp/images/dialog_demo@2x.png
  jp/images/dialog_do1.png
  jp/images/dialog_do1@2x.png
  jp/images/dialog_dont1.png
  jp/images/dialog_dont1@2x.png
  jp/images/dialog_standard.png
  jp/images/dialog_standard@2x.png
  jp/images/dialog_styling.png
  jp/images/dialog_styling@2x.png
Labels: status: verified

#410 Updated slider topic
  en/components/slider.md
  en/images/slider_dark.png
  en/images/slider_dark@2x.png
  en/images/slider_demo.png
  en/images/slider_demo@2x.png
  en/images/slider_disabled.png
  en/images/slider_disabled@2x.png
  en/images/slider_do1.png
  en/images/slider_do1@2x.png
  en/images/slider_do2.png
  en/images/slider_do2@2x.png
  en/images/slider_dont1.png
  en/images/slider_dont1@2x.png
  en/images/slider_dont2.png
  en/images/slider_dont2@2x.png
  en/images/slider_enabled.png
  en/images/slider_enabled@2x.png
  en/images/slider_light.png
  en/images/slider_light@2x.png
  en/images/slider_one-thumb.png
  en/images/slider_one-thumb@2x.png
  en/images/slider_onethumb.png
  en/images/slider_onethumb@2x.png
  en/images/slider_styling.png
  en/images/slider_styling@2x.png
  en/images/slider_two-thumb.png
  en/images/slider_two-thumb@2x.png
  en/images/slider_twothumbs.png
  en/images/slider_twothumbs@2x.png
  jp/images/slider_dark.png
  jp/images/slider_dark@2x.png
  jp/images/slider_demo.png
  jp/images/slider_demo@2x.png
  jp/images/slider_disabled.png
  jp/images/slider_disabled@2x.png
  jp/images/slider_do1.png
  jp/images/slider_do1@2x.png
  jp/images/slider_do2.png
  jp/images/slider_do2@2x.png
  jp/images/slider_dont1.png
  jp/images/slider_dont1@2x.png
  jp/images/slider_dont2.png
  jp/images/slider_dont2@2x.png
  jp/images/slider_enabled.png
  jp/images/slider_enabled@2x.png
  jp/images/slider_light.png
  jp/images/slider_light@2x.png
  jp/images/slider_one-thumb.png
  jp/images/slider_one-thumb@2x.png
  jp/images/slider_onethumb.png
  jp/images/slider_onethumb@2x.png
  jp/images/slider_styling.png
  jp/images/slider_styling@2x.png
  jp/images/slider_two-thumb.png
  jp/images/slider_two-thumb@2x.png
  jp/images/slider_twothumbs.png
  jp/images/slider_twothumbs@2x.png
Labels: status: verified

#408 Updated progress topic
  en/components/progress.md
  en/images/progress_circular-progress-amount.png
  en/images/progress_circular-progress-amount@2x.png
  en/images/progress_circular.png
  en/images/progress_circular@2x.png
  en/images/progress_default.png
  en/images/progress_default@2x.png
  en/images/progress_demo.png
  en/images/progress_demo@2x.png
  en/images/progress_do3.png
  en/images/progress_do3@2x.png
  en/images/progress_dont3.png
  en/images/progress_dont3@2x.png
  en/images/progress_error.png
  en/images/progress_error@2x.png
  en/images/progress_info.png
  en/images/progress_info@2x.png
  en/images/progress_linear-progress-amount.png
  en/images/progress_linear-progress-amount@2x.png
  en/images/progress_linear.png
  en/images/progress_linear@2x.png
  en/images/progress_linearstripes.png
  en/images/progress_linearstripes@2x.png
  en/images/progress_success.png
  en/images/progress_success@2x.png
  en/images/progress_warn.png
  en/images/progress_warn@2x.png
  jp/images/progress_circular-progress-amount.png
  jp/images/progress_circular-progress-amount@2x.png
  jp/images/progress_circular.png
  jp/images/progress_circular@2x.png
  jp/images/progress_default.png
  jp/images/progress_default@2x.png
  jp/images/progress_demo.png
  jp/images/progress_demo@2x.png
  jp/images/progress_do3.png
  jp/images/progress_do3@2x.png
  jp/images/progress_dont3.png
  jp/images/progress_dont3@2x.png
  jp/images/progress_error.png
  jp/images/progress_error@2x.png
  jp/images/progress_info.png
  jp/images/progress_info@2x.png
  jp/images/progress_linear-progress-amount.png
  jp/images/progress_linear-progress-amount@2x.png
  jp/images/progress_linear.png
  jp/images/progress_linear@2x.png
  jp/images/progress_linearstripes.png
  jp/images/progress_linearstripes@2x.png
  jp/images/progress_success.png
  jp/images/progress_success@2x.png
  jp/images/progress_warn.png
  jp/images/progress_warn@2x.png
Labels: status: verified

#409 Updated radio group topic
  en/components/radio-group.md
  en/images/radiogroup_after-label.png
  en/images/radiogroup_after-label@2x.png
  en/images/radiogroup_before-label.png
  en/images/radiogroup_before-label@2x.png
  en/images/radiogroup_disabled-state.png
  en/images/radiogroup_disabled-state@2x.png
  en/images/radiogroup_enabled&disabled-state.png
  en/images/radiogroup_enabled&disabled-state@2x.png
  en/images/radiogroup_enabled-state.png
  en/images/radiogroup_enabled-state@2x.png
  jp/images/radiogroup_after-label.png
  jp/images/radiogroup_after-label@2x.png
  jp/images/radiogroup_before-label.png
  jp/images/radiogroup_before-label@2x.png
  jp/images/radiogroup_disabled-state.png
  jp/images/radiogroup_disabled-state@2x.png
  jp/images/radiogroup_enabled&disabled-state.png
  jp/images/radiogroup_enabled&disabled-state@2x.png
  jp/images/radiogroup_enabled-state.png
  jp/images/radiogroup_enabled-state@2x.png
Labels: status: verified

#414 Updated toast topic
  en/components/toast.md
  en/images/toast_bottom.png
  en/images/toast_bottom@2x.png
  en/images/toast_center.png
  en/images/toast_center@2x.png
  en/images/toast_demo.png
  en/images/toast_demo@2x.png
  en/images/toast_do1.png
  en/images/toast_do1@2x.png
  en/images/toast_do2.png
  en/images/toast_do2@2x.png
  en/images/toast_dont1.png
  en/images/toast_dont1@2x.png
  en/images/toast_dont2.png
  en/images/toast_dont2@2x.png
  en/images/toast_styling.png
  en/images/toast_styling@2x.png
  en/images/toast_top.png
  en/images/toast_top@2x.png
  jp/images/toast_bottom.png
  jp/images/toast_bottom@2x.png
  jp/images/toast_center.png
  jp/images/toast_center@2x.png
  jp/images/toast_demo.png
  jp/images/toast_demo@2x.png
  jp/images/toast_do1.png
  jp/images/toast_do1@2x.png
  jp/images/toast_do2.png
  jp/images/toast_do2@2x.png
  jp/images/toast_dont1.png
  jp/images/toast_dont1@2x.png
  jp/images/toast_dont2.png
  jp/images/toast_dont2@2x.png
  jp/images/toast_styling.png
  jp/images/toast_styling@2x.png
  jp/images/toast_top.png
  jp/images/toast_top@2x.png
Labels: status: verified

#423 Audio/Video Pattern topic update
  en/images/av_player_detach.png
  en/images/av_player_detach@2x.png
  en/images/av_volume_detach.png
  en/images/av_volume_detach@2x.png
  en/patterns/av.md
Labels: localization-pending, status: verified

#424 Avatar + Badge Pattern topic update
  en/images/avatar_badge_detach.png
  en/images/avatar_badge_detach@2x.png
  en/patterns/avatar-badge.md
Labels: localization-pending, status: verified

#426 Details pattern topic update
  en/images/details_detach.png
  en/images/details_detach@2x.png
  en/images/icon_title_detach.png
  en/images/icon_title_detach@2x.png
  en/patterns/details.md
Labels: localization-pending, status: verified

#434 Onboarding pattern topic update
  en/images/onboarding.png
  en/images/onboarding@2x.png
  en/images/onboarding_detach.png
  en/images/onboarding_detach@2x.png
  en/patterns/onboarding.md
Labels: localization-pending, status: verified

#432 Checkbox Group pattern topic update
  en/images/checkbox_group_detach.png
  en/images/checkbox_group_detach@2x.png
  en/patterns/checkbox-group.md
Labels: localization-pending, status: verified

#431 Bar pattern topic update
  en/images/bar_detach.png
  en/images/bar_detach@2x.png
  en/patterns/bar.md
Labels: localization-pending, status: verified

#427 File Upload pattern topic update
  en/images/file-upload_content.png
  en/images/file-upload_content@2x.png
  en/images/file_upload_detach.png
  en/images/file_upload_detach@2x.png
  en/patterns/file-upload.md
Labels: localization-pending, status: verified

#425 Data Visualizations pattern topic update
  en/images/data_visualizations.png
  en/images/data_visualizations@2x.png
  en/images/data_visualizations_detach.png
  en/images/data_visualizations_detach@2x.png
  en/patterns/data-visualizations.md
Labels: localization-pending, status: verified

#417 Updating dropdown topic
  en/components/dropdown.md
  en/images/dropdown_demo.png
  en/images/dropdown_demo@2x.png
  en/images/dropdown_desktop.png
  en/images/dropdown_desktop@2x.png
  en/images/dropdown_header.png
  en/images/dropdown_header@2x.png
  en/images/dropdown_item.png
  en/images/dropdown_item@2x.png
  en/images/dropdown_item_disabled.png
  en/images/dropdown_item_disabled@2x.png
  en/images/dropdown_item_focused.png
  en/images/dropdown_item_focused@2x.png
  en/images/dropdown_item_icon.png
  en/images/dropdown_item_icon@2x.png
  en/images/dropdown_item_idle.png
  en/images/dropdown_item_idle@2x.png
  en/images/dropdown_item_selected.png
  en/images/dropdown_item_selected@2x.png
  en/images/dropdown_item_selected_focused.png
  en/images/dropdown_item_selected_focused@2x.png
  en/images/dropdown_mobile.png
  en/images/dropdown_mobile@2x.png
  en/images/dropdown_styling.png
  en/images/dropdown_styling@2x.png
  jp/images/dropdown_demo.png
  jp/images/dropdown_demo@2x.png
  jp/images/dropdown_desktop.png
  jp/images/dropdown_desktop@2x.png
  jp/images/dropdown_header.png
  jp/images/dropdown_header@2x.png
  jp/images/dropdown_item.png
  jp/images/dropdown_item@2x.png
  jp/images/dropdown_item_disabled.png
  jp/images/dropdown_item_disabled@2x.png
  jp/images/dropdown_item_focused.png
  jp/images/dropdown_item_focused@2x.png
  jp/images/dropdown_item_icon.png
  jp/images/dropdown_item_icon@2x.png
  jp/images/dropdown_item_idle.png
  jp/images/dropdown_item_idle@2x.png
  jp/images/dropdown_item_selected.png
  jp/images/dropdown_item_selected@2x.png
  jp/images/dropdown_item_selected_focused.png
  jp/images/dropdown_item_selected_focused@2x.png
  jp/images/dropdown_mobile.png
  jp/images/dropdown_mobile@2x.png
  jp/images/dropdown_styling.png
  jp/images/dropdown_styling@2x.png
Labels: localization-pending, status: verified

#435 Pricing Plan pattern topic update
  en/images/pricing_plan_detach.png
  en/images/pricing_plan_detach@2x.png
  en/patterns/pricing-plan.md
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified

#437 Adding the new Skeleton List topic to the ToC
  en/sidebar-toc/toc.yml
Labels: localization-pending, status: verified

#440 Image Manipulation pattern topic update
  en/images/image-manip_layout.png
  en/images/image-manip_layout@2x.png
  en/images/image_manipulation_detach.png
  en/images/image_manipulation_detach@2x.png
  en/patterns/image-manipulation.md
  jp/images/image-manip_layout.png
  jp/images/image-manip_layout@2x.png
Labels: localization-pending, status: verified

#438 Tiles pattern topic update
  en/images/tiles_detach.png
  en/images/tiles_detach@2x.png
  en/patterns/tiles.md
Labels: localization-pending, status: verified

#444 Lists pattern topic update
  en/images/lists_detach.png
  en/images/lists_detach@2x.png
  en/images/lists_horizontal_vertical_detach.png
  en/images/lists_horizontal_vertical_detach@2x.png
  en/patterns/lists.md
Labels: localization-pending, status: verified

#439 User Profile pattern topic update
  en/images/edit_profile_demo.png
  en/images/edit_profile_demo@2x.png
  en/images/edit_profile_detach.png
  en/images/edit_profile_detach@2x.png
  en/images/profile_demo.png
  en/images/profile_demo@2x.png
  en/images/profile_detach.png
  en/images/profile_detach@2x.png
  en/images/profile_small.png
  en/images/profile_small@2x.png
  en/patterns/user-profile.md
Labels: localization-pending, status: verified

#445 Tree Grid pattern topic update
  en/images/tree_grid.png
  en/images/tree_grid@2x.png
  en/images/tree_grid_detach.png
  en/images/tree_grid_detach@2x.png
  en/patterns/tree-grid.md
Labels: localization-pending, status: verified

#420 Localization 0701 vnext
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/bottom-nav.md
  jp/components/button-group.md
  jp/components/button.md
  jp/components/calendar.md
  jp/components/card-skeleton.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/checkbox.md
  jp/components/chips.md
  jp/components/date-picker.md
  jp/components/dialog.md
  jp/components/grid-column-pinning.md
  jp/components/grid-grouping.md
  jp/components/grid-summaries.md
  jp/components/grid.md
  jp/components/hyperlink.md
  jp/components/icon.md
  jp/components/list-custom.md
  jp/components/list.md
  jp/components/nav-drawer.md
  jp/components/navbar.md
  jp/components/progress.md
  jp/components/radio-group.md
  jp/components/slider.md
  jp/components/snackbar.md
  jp/components/switch.md
  jp/components/tabs.md
  jp/components/text.md
  jp/components/time-picker.md
  jp/components/toast.md
  jp/components/tooltip.md
  jp/creating-an-artboard.md
  jp/known-issues.md
  jp/patterns/av.md
  jp/patterns/avatar-badge.md
  jp/patterns/checkbox-group.md
  jp/patterns/details.md
  jp/patterns/file-upload.md
  jp/patterns/form.md
  jp/patterns/gallery.md
  jp/patterns/image-manipulation.md
  jp/patterns/user-profile.md
  jp/sidebar-toc/toc.yml
  jp/sync-themes-plugin.md
Labels: localized, status: verified

#449 Grid pattern topic update
  en/images/grid.png
  en/images/grid@2x.png
  en/images/grid_detach.png
  en/images/grid_detach@2x.png
  en/patterns/grid.md
Labels: localization-pending, status: verified

#452 Hierarchical Grid pattern topic update
  en/images/hierarchical_grid.png
  en/images/hierarchical_grid@2x.png
  en/images/hierarchical_grid_detach.png
  en/images/hierarchical_grid_detach@2x.png
  en/patterns/hierarchical-grid.md
Labels: localization-pending, status: verified

#433 Menu pattern topic update
  en/images/menu.png
  en/images/menu@2x.png
  en/images/menu_detach.png
  en/images/menu_detach@2x.png
  en/images/menu_horizontal.png
  en/images/menu_horizontal@2x.png
  en/images/menu_vertical.png
  en/images/menu_vertical@2x.png
  en/patterns/menu.md
Labels: localization-pending, status: verified
