Repository IgniteUI/indigo-design-docfx, pull requests merged in 2021-08, with the labels that each got.

#534 [JA] Onboarding topics UI KIts
  jp/creating-artboard-adobexd.md
  jp/creating-artboard-sketch.md
  jp/getting-started.md
  jp/images/Creating_An_Artboard_Sketch2.png
  jp/images/Creating_An_Artboard_Sketch2@2x.png
  jp/images/Creating_An_Artboard_XD1.png
  jp/images/Creating_An_Artboard_XD1@2x.png
  jp/images/Creating_An_Artboard_XD2.png
  jp/images/Creating_An_Artboard_XD2@2x.png
  jp/images/Creating_An_Artboard_XD3.png
  jp/images/Creating_An_Artboard_XD3@2x.png
  jp/images/getting-started-sketch-artboard.png
  jp/images/getting-started-sketch-artboard@2x.png
  jp/images/getting-started-sketch0.png
  jp/images/getting-started-sketch0@2x.png
  jp/images/getting-started-sketch1.png
  jp/images/getting-started-sketch1@2x.png
  jp/images/getting-started-sketch2.png
  jp/images/getting-started-sketch2@2x.png
  jp/images/getting-started-sketch3.png
  jp/images/getting-started-sketch3@2x.png
  jp/images/getting-started-sketch4.png
  jp/images/getting-started-sketch4@2x.png
  jp/images/getting-started-sketch5.png
  jp/images/getting-started-sketch5@2x.png
  jp/images/getting-started-sketch6.png
  jp/images/getting-started-sketch6@2x.png
  jp/images/getting-started-sketch7.png
  jp/images/getting-started-sketch7@2x.png
  jp/images/getting-started-xd-artboard.png
  jp/images/getting-started-xd-artboard@2x.png
  jp/images/getting-startedxd0.png
  jp/images/getting-startedxd0@2x.png
  jp/images/getting-startedxd1.png
  jp/images/getting-startedxd1@2x.png
  jp/images/getting-startedxd2.png
  jp/images/getting-startedxd2@2x.png
  jp/images/getting-startedxd3.png
  jp/images/getting-startedxd3@2x.png
  jp/images/getting-startedxd4.png
  jp/images/getting-startedxd4@2x.png
  jp/images/getting-startedxd5.png
  jp/images/getting-startedxd5@2x.png
  jp/images/getting-startedxd6.png
  jp/images/getting-startedxd6@2x.png
  jp/images/getting-startedxd7.png
  jp/images/getting-startedxd7@2x.png
  jp/sidebar-toc/toc.yml
Labels: localized, status: verified

#529 Styling topics update for XD
  en/components/column-chart.md
  en/components/line-chart.md
  en/components/skeleton-charts.md
  en/components/spline-chart.md
  en/components/step-line-chart.md
  en/images/Illustrations_Avatar.png
  en/images/Illustrations_Avatar@2x.png
  en/images/Illustrations_Cannot_Find.png
  en/images/Illustrations_Cannot_Find@2x.png
  en/images/Illustrations_Empty_State.png
  en/images/Illustrations_Empty_State@2x.png
  en/images/Illustrations_Error_404.png
  en/images/Illustrations_Error_404@2x.png
  en/images/Illustrations_Onboarding.png
  en/images/Illustrations_Onboarding@2x.png
  en/images/Illustrations_Payment.png
  en/images/Illustrations_Payment@2x.png
  en/images/colors-palette-xd1.png
  en/images/colors-palette-xd1@2x.png
  en/images/colors-palette-xd2.png
  en/images/colors-palette-xd2@2x.png
  en/images/colors-palette-xd3.png
  en/images/colors-palette-xd3@2x.png
  en/images/colors_custom6.png
  en/images/colors_custom6@2x.png
  en/images/colors_custom7.png
  en/images/colors_custom7@2x.png
  en/images/colors_custom8.png
  en/images/colors_custom8@2x.png
  en/images/icons_add10.png
  en/images/icons_add10@2x.png
  en/images/icons_add11.png
  en/images/icons_add11@2x.png
  en/images/icons_add6.png
  en/images/icons_add6@2x.png
  en/images/icons_add7.png
  en/images/icons_add7@2x.png
  en/images/icons_add8.png
  en/images/icons_add8@2x.png
  en/images/icons_add9.png
  en/images/icons_add9@2x.png
  en/images/illustrations_default.png
  en/images/text_layers_xd.png
  en/images/text_layers_xd@2x.png
  en/images/typography_custom4.png
  en/images/typography_custom4@2x.png
  en/images/typography_custom5.png
  en/images/typography_custom5@2x.png
  en/images/typography_default.png
  en/images/typography_default@2x.png
  en/sidebar-toc/toc.yml
  en/style/colors.md
  en/style/elevation.md
  en/style/illustrations.md
  en/style/material-icons.md
  en/style/styling-overview.md
  en/style/typography.md
Labels: status: verified

#531 Updated Components Overview topic to also mention Adobe XD
  README.md
  en/components/components-overview.md
  en/images/components-page-xd.png
  en/images/components-page.png
  en/known-issues.md
  en/style/typography.md
  jp/known-issues.md
  jp/style/typography.md
Labels: localization-pending, status: verified

#532 Updated Components Styling sections
  en/components/avatar.md
  en/components/badge.md
  en/components/bottom-nav.md
  en/components/bullet-graph.md
  en/components/button-group.md
  en/components/button.md
  en/components/calendar.md
  en/components/card.md
  en/components/carousel.md
  en/components/checkbox.md
  en/components/chips.md
  en/components/combo.md
  en/components/date-picker.md
  en/components/dialog.md
  en/components/dropdown.md
  en/components/expansion-panel.md
  en/components/grid-excel-style-filter.md
  en/components/grid-paging.md
  en/components/grid-summaries.md
  en/components/grid-toolbar.md
  en/components/icon.md
  en/components/linear-gauge.md
  en/components/list.md
  en/components/nav-drawer.md
  en/components/navbar.md
  en/components/progress.md
  en/components/radial-gauge.md
  en/components/radio-group.md
  en/components/slider.md
  en/components/snackbar.md
  en/components/switch.md
  en/components/tabs.md
  en/components/text.md
  en/components/time-picker.md
  en/components/toast.md
  en/components/tooltip.md
  en/components/tree-grid.md
Labels: localization-pending, status: verified

#535 Components topics update for XD state feature
  en/components/bottom-nav.md
  en/components/bullet-graph.md
  en/components/button.md
  en/components/carousel.md
  en/components/checkbox.md
  en/components/chips.md
  en/components/column-chart.md
  en/components/combo.md
  en/components/dropdown.md
  en/components/grid-advanced-filter.md
  en/components/grid-column-hiding.md
  en/components/grid-column-moving.md
  en/components/grid-column-pinning.md
  en/components/grid-column-resizing.md
  en/components/grid-editing.md
  en/components/grid-excel-style-filter.md
  en/components/grid-grouping.md
  en/components/grid-row-filter.md
  en/components/grid-row-selection.md
  en/components/grid-sorting.md
  en/components/grid-summaries.md
  en/components/grid.md
  en/components/input.md
  en/components/line-chart.md
  en/components/linear-gauge.md
  en/components/list-custom.md
  en/components/list-skeleton.md
  en/components/list.md
  en/components/nav-drawer.md
  en/components/progress.md
  en/components/radial-gauge.md
  en/components/radio-group.md
  en/components/slider.md
  en/components/spline-chart.md
  en/components/step-line-chart.md
  en/components/switch.md
  en/components/tabs.md
  en/components/time-picker.md
  en/components/tree-grid-skeleton.md
  en/components/tree-grid.md
Labels: localization-pending, status: verified

#533 Updated Grids and List topics
  en/components/grid.md
  en/components/hierarchical-grid.md
  en/components/list-custom.md
  en/components/list-item.md
  en/components/list-skeleton.md
  en/components/list.md
  en/components/tree-grid.md
  en/images/actions_xd.png
  en/images/actions_xd@2x.png
  en/images/actions_xd_skeleton.png
  en/images/actions_xd_skeleton@2x.png
  en/images/hgrid_layers_panel_adobe_xd.png
  en/images/hgrid_layers_panel_adobe_xd@2x.png
  en/images/layers_panel_adobe_xd.png
  en/images/layers_panel_adobe_xd@2x.png
  en/images/list_item_demo.png
  en/images/list_item_demo@2x.png
  en/images/list_item_styling.png
  en/images/list_item_styling@2x.png
  en/images/tgrid_layers_panel_adobe_xd.png
  en/images/tgrid_layers_panel_adobe_xd@2x.png
  en/images/thumbnail_xd.png
  en/images/thumbnail_xd@2x.png
  en/images/thumbnail_xd_skeleton.png
  en/images/thumbnail_xd_skeleton@2x.png
  en/sidebar-toc/toc.yml
  jp/images/actions_xd.png
  jp/images/actions_xd@2x.png
  jp/images/actions_xd_skeleton.png
  jp/images/actions_xd_skeleton@2x.png
  jp/images/hgrid_layers_panel_adobe_xd.png
  jp/images/hgrid_layers_panel_adobe_xd@2x.png
  jp/images/layers_panel_adobe_xd.png
  jp/images/layers_panel_adobe_xd@2x.png
  jp/images/list_item_demo.png
  jp/images/list_item_demo@2x.png
  jp/images/list_item_styling.png
  jp/images/list_item_styling@2x.png
  jp/images/tgrid_layers_panel_adobe_xd.png
  jp/images/tgrid_layers_panel_adobe_xd@2x.png
  jp/images/thumbnail_xd.png
  jp/images/thumbnail_xd@2x.png
  jp/images/thumbnail_xd_skeleton.png
  jp/images/thumbnail_xd_skeleton@2x.png
Labels: localization-pending, status: verified

#537 Updated components for mentioning layer deletion in Adobe XD
  en/components/bottom-nav.md
  en/components/bullet-graph.md
  en/components/button-group.md
  en/components/button.md
  en/components/calendar.md
  en/components/card-skeleton.md
  en/components/card.md
  en/components/carousel.md
  en/components/chips.md
  en/components/column-chart.md
  en/components/combo.md
  en/components/date-picker.md
  en/components/dialog.md
  en/components/dropdown.md
  en/components/grid-toolbar.md
  en/components/input.md
  en/components/line-chart.md
  en/components/linear-gauge.md
  en/components/nav-drawer.md
  en/components/navbar.md
  en/components/spline-chart.md
  en/components/step-line-chart.md
  en/components/tabs.md
  en/components/time-picker.md
  en/images/datepicker_buttons.png
  en/images/datepicker_buttons@2x.png
  en/images/datepicker_demo.png
  en/images/datepicker_demo@2x.png
  en/images/datepicker_do2.png
  en/images/datepicker_do2@2x.png
  en/images/datepicker_dont2.png
  en/images/datepicker_dont2@2x.png
  en/images/datepicker_dropdown.png
  en/images/datepicker_dropdown@2x.png
  en/images/datepicker_monday.png
  en/images/datepicker_monday@2x.png
  en/images/datepicker_range.png
  en/images/datepicker_range@2x.png
  en/images/datepicker_selection.png
  en/images/datepicker_selection@2x.png
  en/images/datepicker_weeknumbers.png
  en/images/datepicker_weeknumbers@2x.png
  jp/images/datepicker_buttons.png
  jp/images/datepicker_buttons@2x.png
  jp/images/datepicker_demo.png
  jp/images/datepicker_demo@2x.png
  jp/images/datepicker_do2.png
  jp/images/datepicker_do2@2x.png
  jp/images/datepicker_dont2.png
  jp/images/datepicker_dont2@2x.png
  jp/images/datepicker_dropdown.png
  jp/images/datepicker_dropdown@2x.png
  jp/images/datepicker_monday.png
  jp/images/datepicker_monday@2x.png
  jp/images/datepicker_range.png
  jp/images/datepicker_range@2x.png
  jp/images/datepicker_selection.png
  jp/images/datepicker_selection@2x.png
  jp/images/datepicker_weeknumbers.png
  jp/images/datepicker_weeknumbers@2x.png
Labels: status: verified, localization-pending

#539 Updated topics with _Overrides explanation
  en/components/components-overview.md
  en/creating-artboard-adobexd.md
  en/creating-artboard-sketch.md
Labels: status: verified, localization-pending

#548 Update graphic design to code
  en/getting-started.md
  en/images/Indigo-Design-how-it-works.png
  en/images/indigo-design-how-it-works@2x.png
  jp/getting-started.md
  jp/images/Indigo-Design-how-it-works.png
  jp/images/indigo-design-how-it-works@2x.png
Labels: status: verified

#546 New topics for Banner and Expansion Panel
  en/components/banner.md
  en/components/expansion-panel.md
  en/images/banner_actions.png
  en/images/banner_actions@2x.png
  en/images/banner_demo.png
  en/images/banner_demo@2x.png
  en/images/banner_do.png
  en/images/banner_do1.png
  en/images/banner_do1@2x.png
  en/images/banner_do2@2x.png
  en/images/banner_do2x.png
  en/images/banner_do@2x.png
  en/images/banner_dont.png
  en/images/banner_dont1.png
  en/images/banner_dont1@2x.png
  en/images/banner_dont2.png
  en/images/banner_dont2@2x.png
  en/images/banner_dont@2x.png
  en/images/banner_message.png
  en/images/banner_message@2x.png
  en/images/banner_styling.png
  en/images/banner_styling@2x.png
  en/images/expansion_panel_active.png
  en/images/expansion_panel_active@2x.png
  en/images/expansion_panel_body.png
  en/images/expansion_panel_body@2x.png
  en/images/expansion_panel_demo.png
  en/images/expansion_panel_demo@2x.png
  en/images/expansion_panel_disabled.png
  en/images/expansion_panel_disabled@2x.png
  en/images/expansion_panel_do1.png
  en/images/expansion_panel_do1@2x.png
  en/images/expansion_panel_dont1.png
  en/images/expansion_panel_dont1@2x.png
  en/images/expansion_panel_header1.png
  en/images/expansion_panel_header1@2x.png
  en/images/expansion_panel_header2.png
  en/images/expansion_panel_header2@2x.png
  en/images/expansion_panel_styling.png
  en/images/expansion_panel_styling@2x.png
  en/sidebar-toc/toc.yml
Labels: enhancement, status: verified

#553 Add useWarningsAsErrors option
  en/appbuilder/generate-app/run-application-locally.md
  en/appbuilder/preview-code.md
  en/appbuilder/single-page-apps-and-navigation.md
  en/codegen/after-codegen.md
  en/components/banner.md
  en/components/card.md
  en/components/linear-gauge.md
  en/components/text.md
  en/getting-started-old.md
  en/getting-started.md
  en/global.json
  en/style/illustrations.md
  en/sync-themes-plugin.md
  package-lock.json
  package.json
Labels: status: verified

#552 Update embedded videos markup to make them responsive.
  en/appbuilder/app-themes/app-themes.md
  en/appbuilder/flex-layouts/flex-layouts.md
  en/appbuilder/generate-app/generate-app-overview.md
  en/appbuilder/getting-started.md
  en/appbuilder/indigo-design-app-builder-components.md
  en/appbuilder/interactions.md
  en/appbuilder/preview-code.md
  en/appbuilder/single-page-apps-and-navigation.md
  en/video-tutorials.md
  jp/appbuilder/app-themes/app-themes.md
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/appbuilder/generate-app/generate-app-overview.md
  jp/appbuilder/getting-started.md
  jp/appbuilder/indigo-design-app-builder-components.md
  jp/appbuilder/interactions.md
  jp/appbuilder/preview-code.md
  jp/appbuilder/single-page-apps-and-navigation.md
  jp/video-tutorials.md
Labels: status: verified

#555 update videos markup to make them responsive.
  en/appbuilder/app-themes/app-themes.md
  en/appbuilder/flex-layouts/flex-layouts.md
  en/appbuilder/generate-app/generate-app-overview.md
  en/appbuilder/getting-started.md
  en/appbuilder/indigo-design-app-builder-components.md
  en/appbuilder/interactions.md
  en/appbuilder/preview-code.md
  en/appbuilder/single-page-apps-and-navigation.md
  en/video-tutorials.md
  jp/appbuilder/app-themes/app-themes.md
  jp/appbuilder/flex-layouts/flex-layouts.md
  jp/appbuilder/generate-app/generate-app-overview.md
  jp/appbuilder/getting-started.md
  jp/appbuilder/indigo-design-app-builder-components.md
  jp/appbuilder/interactions.md
  jp/appbuilder/preview-code.md
  jp/appbuilder/single-page-apps-and-navigation.md
  jp/video-tutorials.md
Labels: status: verified

#556 Add useWarningsAsErrors option -master
  en/appbuilder/generate-app/run-application-locally.md
  en/appbuilder/preview-code.md
  en/appbuilder/single-page-apps-and-navigation.md
  en/codegen/after-codegen.md
  en/components/card.md
  en/components/column-chart.md
  en/components/linear-gauge.md
  en/components/spline-chart.md
  en/components/step-line-chart.md
  en/components/text.md
  en/getting-started-old.md
  en/global.json
  en/sync-themes-plugin.md
  package-lock.json
  package.json
Labels: status: verified

#560 [JP] Adding the latest topic changes - Combo, Dropdown, Text Area
  jp/components/combo.md
  jp/components/dropdown.md
  jp/components/input.md
  jp/components/linear-gauge.md
  jp/components/textarea.md
  jp/sidebar-toc/toc.yml
Labels: status: verified, localized

#561 [JP] Localization fixes after testing - vNext
  jp/components/banner.md
  jp/components/card-skeleton.md
  jp/components/carousel.md
  jp/components/chips.md
  jp/components/combo.md
  jp/components/components-overview.md
  jp/components/grid-advanced-filter.md
  jp/components/grid-column-hiding.md
  jp/components/grid-excel-style-filter.md
  jp/components/grid-grouping.md
  jp/components/grid-sorting.md
  jp/components/grid.md
  jp/components/hierarchical-grid.md
  jp/components/input.md
  jp/components/list-skeleton.md
  jp/components/nav-drawer.md
  jp/components/progress.md
  jp/components/radial-gauge.md
  jp/components/spline-chart.md
  jp/components/step-line-chart.md
  jp/components/tabs.md
  jp/components/textarea.md
  jp/components/time-picker.md
  jp/components/tree-grid-skeleton.md
  jp/creating-artboard-adobexd.md
  jp/creating-artboard-sketch.md
  jp/style/material-icons.md
Labels: status: verified, localized

#562 [JP] Radial Gauge topic fix
  jp/components/radial-gauge.md
Labels: status: verified, localized
