Repository IgniteUI/indigo-design-docfx, pull requests merged in 2022-06, with the labels that each got.

#632 [JA] Adding the latest topic changes - Button, Chips, List - vNext
  jp/components/button.md
  jp/components/chips.md
  jp/components/list-custom.md
  jp/creating-artboard-adobexd.md
  jp/creating-artboard-sketch.md
Labels: status: verified, localized

#634 Update seo cta banners - vnext
  en/images/marketing/indigo-design-transofrm-sketch-xd.gif
  jp/images/marketing/indigo-design-transofrm-sketch-xd.gif
  package-lock.json
  package.json
Labels: status: verified, SEO

#635 Update seo cta banners - master
  en/images/marketing/indigo-design-transofrm-sketch-xd.gif
  jp/images/marketing/indigo-design-transofrm-sketch-xd.gif
  package-lock.json
  package.json
Labels: SEO
