Repository IgniteUI/indigo-design-docfx, pull requests merged in 2022-04, with the labels that each got.

#610 Image update in the Material Icons topic
  en/images/icons_add4.png
  en/images/icons_add4@2x.png
  jp/images/icons_add4.png
  jp/images/icons_add4@2x.png
Labels: status: awaiting-test, status: verified

#611 Adobe XD image update in Components topic
  en/images/components-page-xd.png
  en/images/components-page-xd@2x.png
  jp/images/components-page-xd.png
  jp/images/components-page-xd@2x.png
Labels: status: awaiting-test

#612 Images update in Responsive layouts topics
  en/images/layout-columns.png
  en/images/layout-rows.png
  en/images/sketch_fixed_size.png
  en/images/stack-column-xd.png
  en/images/stack-row-xd.png
  jp/images/layout-columns.png
  jp/images/layout-rows.png
  jp/images/sketch_fixed_size.png
  jp/images/stack-column-xd.png
  jp/images/stack-row-xd.png
Labels: status: verified

#615 Images updated in the Card topic
  en/images/card_actions_buttons_icons.png
  en/images/card_actions_buttons_icons@2x.png
  en/images/card_actions_icons_buttons.png
  en/images/card_actions_icons_buttons@2x.png
  en/images/card_actions_just_buttons.png
  en/images/card_actions_just_buttons@2x.png
  en/images/card_actions_just_buttons_icons.png
  en/images/card_actions_just_buttons_icons@2x.png
  en/images/card_actions_just_icons.png
  en/images/card_actions_just_icons@2x.png
  en/images/card_actions_just_icons_buttons.png
  en/images/card_actions_just_icons_buttons@2x.png
  en/images/card_demo.png
  en/images/card_demo@2x.png
  en/images/card_skeleton_actions_buttons_icons.png
  en/images/card_skeleton_actions_buttons_icons@2x.png
  en/images/card_skeleton_actions_icons_buttons.png
  en/images/card_skeleton_actions_icons_buttons@2x.png
  en/images/card_skeleton_actions_just_buttons.png
  en/images/card_skeleton_actions_just_buttons@2x.png
  en/images/card_skeleton_actions_just_buttons_icons.png
  en/images/card_skeleton_actions_just_buttons_icons@2x.png
  en/images/card_skeleton_actions_just_icons.png
  en/images/card_skeleton_actions_just_icons@2x.png
  en/images/card_skeleton_actions_just_icons_buttons.png
  en/images/card_skeleton_actions_just_icons_buttons@2x.png
  en/images/card_skeleton_dont.png
  en/images/card_skeleton_dont@2x.png
  en/images/card_styling.png
  en/images/card_styling@2x.png
  jp/images/card_actions_buttons_icons.png
  jp/images/card_actions_buttons_icons@2x.png
  jp/images/card_actions_icons_buttons.png
  jp/images/card_actions_icons_buttons@2x.png
  jp/images/card_actions_just_buttons.png
  jp/images/card_actions_just_buttons@2x.png
  jp/images/card_actions_just_buttons_icons.png
  jp/images/card_actions_just_buttons_icons@2x.png
  jp/images/card_actions_just_icons.png
  jp/images/card_actions_just_icons@2x.png
  jp/images/card_actions_just_icons_buttons.png
  jp/images/card_actions_just_icons_buttons@2x.png
  jp/images/card_demo.png
  jp/images/card_demo@2x.png
  jp/images/card_skeleton_actions_buttons_icons.png
  jp/images/card_skeleton_actions_buttons_icons@2x.png
  jp/images/card_skeleton_actions_icons_buttons.png
  jp/images/card_skeleton_actions_icons_buttons@2x.png
  jp/images/card_skeleton_actions_just_buttons.png
  jp/images/card_skeleton_actions_just_buttons@2x.png
  jp/images/card_skeleton_actions_just_buttons_icons.png
  jp/images/card_skeleton_actions_just_buttons_icons@2x.png
  jp/images/card_skeleton_actions_just_icons.png
  jp/images/card_skeleton_actions_just_icons@2x.png
  jp/images/card_skeleton_actions_just_icons_buttons.png
  jp/images/card_skeleton_actions_just_icons_buttons@2x.png
  jp/images/card_skeleton_dont.png
  jp/images/card_skeleton_dont@2x.png
  jp/images/card_styling.png
  jp/images/card_styling@2x.png
Labels: status: verified

#616 Images updated in the Combo topic
  en/images/combo_item_focused.png
  en/images/combo_item_focused@2x.png
  en/images/combo_item_idle.png
  en/images/combo_item_idle@2x.png
  en/images/combo_item_selected.png
  en/images/combo_item_selected@2x.png
  en/images/combo_item_selected_focused.png
  en/images/combo_item_selected_focused@2x.png
  en/images/combo_styling.png
  en/images/combo_styling@2x.png
  jp/images/combo_item_focused.png
  jp/images/combo_item_focused@2x.png
  jp/images/combo_item_idle.png
  jp/images/combo_item_idle@2x.png
  jp/images/combo_item_selected.png
  jp/images/combo_item_selected@2x.png
  jp/images/combo_item_selected_focused.png
  jp/images/combo_item_selected_focused@2x.png
  jp/images/combo_styling.png
  jp/images/combo_styling@2x.png
Labels: status: verified

#617 Images updated in the Date Picker topic
  en/images/datepicker_demo.png
  en/images/datepicker_demo@2x.png
  en/images/datepicker_do1.png
  en/images/datepicker_do1@2x.png
  en/images/datepicker_do2.png
  en/images/datepicker_do2@2x.png
  en/images/datepicker_dont1.png
  en/images/datepicker_dont1@2x.png
  en/images/datepicker_dont2.png
  en/images/datepicker_dont2@2x.png
  en/images/datepicker_dropdown.png
  en/images/datepicker_dropdown@2x.png
  en/images/datepicker_horizontal.png
  en/images/datepicker_horizontal@2x.png
  en/images/datepicker_monday.png
  en/images/datepicker_monday@2x.png
  en/images/datepicker_range.png
  en/images/datepicker_range@2x.png
  en/images/datepicker_selection.png
  en/images/datepicker_selection@2x.png
  en/images/datepicker_styling.png
  en/images/datepicker_styling@2x.png
  en/images/datepicker_vertical.png
  en/images/datepicker_vertical@2x.png
  en/images/datepicker_weeknumbers.png
  en/images/datepicker_weeknumbers@2x.png
  jp/images/datepicker_demo.png
  jp/images/datepicker_demo@2x.png
  jp/images/datepicker_do1.png
  jp/images/datepicker_do1@2x.png
  jp/images/datepicker_do2.png
  jp/images/datepicker_do2@2x.png
  jp/images/datepicker_dont1.png
  jp/images/datepicker_dont1@2x.png
  jp/images/datepicker_dont2.png
  jp/images/datepicker_dont2@2x.png
  jp/images/datepicker_dropdown.png
  jp/images/datepicker_dropdown@2x.png
  jp/images/datepicker_horizontal.png
  jp/images/datepicker_horizontal@2x.png
  jp/images/datepicker_monday.png
  jp/images/datepicker_monday@2x.png
  jp/images/datepicker_range.png
  jp/images/datepicker_range@2x.png
  jp/images/datepicker_selection.png
  jp/images/datepicker_selection@2x.png
  jp/images/datepicker_styling.png
  jp/images/datepicker_styling@2x.png
  jp/images/datepicker_vertical.png
  jp/images/datepicker_vertical@2x.png
  jp/images/datepicker_weeknumbers.png
  jp/images/datepicker_weeknumbers@2x.png
Labels: status: verified

#618 Images updated in the Grid Excel Style Filter topic
  en/images/grid.png
  en/images/grid@2x.png
  en/images/grid_excel_style_filter_demo.png
  en/images/grid_excel_style_filter_demo@2x.png
  en/images/grid_excel_style_filter_densities.png
  en/images/grid_excel_style_filter_densities@2x.png
  en/images/tree_grid.png
  en/images/tree_grid@2x.png
  jp/images/grid.png
  jp/images/grid@2x.png
  jp/images/grid_excel_style_filter_demo.png
  jp/images/grid_excel_style_filter_demo@2x.png
  jp/images/grid_excel_style_filter_densities.png
  jp/images/grid_excel_style_filter_densities@2x.png
  jp/images/tree_grid.png
  jp/images/tree_grid@2x.png
Labels: status: verified

#620 Images updated in the Snackbar topic
  en/images/snackbar_demo.png
  en/images/snackbar_demo@2x.png
  en/images/snackbar_do1.png
  en/images/snackbar_do1@2x.png
  en/images/snackbar_do2.png
  en/images/snackbar_do2@2x.png
  en/images/snackbar_do3.png
  en/images/snackbar_do3@2x.png
  en/images/snackbar_dont1.png
  en/images/snackbar_dont1@2x.png
  en/images/snackbar_dont2.png
  en/images/snackbar_dont2@2x.png
  en/images/snackbar_dont3.png
  en/images/snackbar_dont3@2x.png
  en/images/snackbar_styling.png
  en/images/snackbar_styling@2x.png
  jp/images/snackbar_demo.png
  jp/images/snackbar_demo@2x.png
  jp/images/snackbar_do1.png
  jp/images/snackbar_do1@2x.png
  jp/images/snackbar_do2.png
  jp/images/snackbar_do2@2x.png
  jp/images/snackbar_do3.png
  jp/images/snackbar_do3@2x.png
  jp/images/snackbar_dont1.png
  jp/images/snackbar_dont1@2x.png
  jp/images/snackbar_dont2.png
  jp/images/snackbar_dont2@2x.png
  jp/images/snackbar_dont3.png
  jp/images/snackbar_dont3@2x.png
  jp/images/snackbar_styling.png
  jp/images/snackbar_styling@2x.png
Labels: status: awaiting-test, localization-pending

#621 Images updated in the Switch topic
  en/images/switch_demo.png
  en/images/switch_demo@2x.png
  en/images/switch_do3.png
  en/images/switch_do3@2x.png
  en/images/switch_dont3.png
  en/images/switch_dont3@2x.png
  en/images/switch_enabled&disabled-state.png
  en/images/switch_enabled&disabled-state@2x.png
  en/images/switch_label-after.png
  en/images/switch_label-after@2x.png
  en/images/switch_label-before.png
  en/images/switch_label-before@2x.png
  en/images/switch_off.png
  en/images/switch_off@2x.png
  en/images/switch_off_disabled.png
  en/images/switch_off_disabled@2x.png
  en/images/switch_on.png
  en/images/switch_on@2x.png
  en/images/switch_on_disabled.png
  en/images/switch_on_disabled@2x.png
  en/images/switch_styling.png
  en/images/switch_styling@2x.png
  jp/images/switch_demo.png
  jp/images/switch_demo@2x.png
  jp/images/switch_do3.png
  jp/images/switch_do3@2x.png
  jp/images/switch_dont3.png
  jp/images/switch_dont3@2x.png
  jp/images/switch_enabled&disabled-state.png
  jp/images/switch_enabled&disabled-state@2x.png
  jp/images/switch_label-after.png
  jp/images/switch_label-after@2x.png
  jp/images/switch_label-before.png
  jp/images/switch_label-before@2x.png
  jp/images/switch_off.png
  jp/images/switch_off@2x.png
  jp/images/switch_off_disabled.png
  jp/images/switch_off_disabled@2x.png
  jp/images/switch_on.png
  jp/images/switch_on@2x.png
  jp/images/switch_on_disabled.png
  jp/images/switch_on_disabled@2x.png
  jp/images/switch_styling.png
  jp/images/switch_styling@2x.png
Labels: status: verified

#627 Updated Badge topic
  en/components/badge.md
  en/images/badge_default.png
  en/images/badge_default@2x.png
  en/images/badge_error.png
  en/images/badge_error@2x.png
  en/images/badge_info.png
  en/images/badge_info@2x.png
  en/images/badge_success.png
  en/images/badge_success@2x.png
  en/images/badge_warn.png
  en/images/badge_warn@2x.png
  jp/images/badge_default.png
  jp/images/badge_default@2x.png
  jp/images/badge_error.png
  jp/images/badge_error@2x.png
  jp/images/badge_info.png
  jp/images/badge_info@2x.png
  jp/images/badge_success.png
  jp/images/badge_success@2x.png
  jp/images/badge_warn.png
  jp/images/badge_warn@2x.png
Labels: status: verified, localization-pending

#626 Updated text in the Avatar topic
  en/components/avatar.md
Labels: status: verified, localization-pending

#624 Updated images and text in the Dropdown topic
  en/components/dropdown.md
  en/images/dropdown_comfortable.png
  en/images/dropdown_comfortable@2x.png
  en/images/dropdown_compact.png
  en/images/dropdown_compact@2x.png
  en/images/dropdown_cosy.png
  en/images/dropdown_cosy@2x.png
  en/images/dropdown_desktop.png
  en/images/dropdown_desktop@2x.png
  en/images/dropdown_do1.png
  en/images/dropdown_do1@2x.png
  en/images/dropdown_dont1.png
  en/images/dropdown_dont1@2x.png
  en/images/dropdown_item_label.png
  en/images/dropdown_item_label@2x.png
  en/images/dropdown_mobile.png
  en/images/dropdown_mobile@2x.png
  jp/images/dropdown_comfortable.png
  jp/images/dropdown_comfortable@2x.png
  jp/images/dropdown_compact.png
  jp/images/dropdown_compact@2x.png
  jp/images/dropdown_cosy.png
  jp/images/dropdown_cosy@2x.png
  jp/images/dropdown_desktop.png
  jp/images/dropdown_desktop@2x.png
  jp/images/dropdown_do1.png
  jp/images/dropdown_do1@2x.png
  jp/images/dropdown_dont1.png
  jp/images/dropdown_dont1@2x.png
  jp/images/dropdown_item_label.png
  jp/images/dropdown_item_label@2x.png
  jp/images/dropdown_mobile.png
  jp/images/dropdown_mobile@2x.png
Labels: status: verified, localization-pending

#623 Updated images and text in the Button topic
  en/components/button.md
  en/images/button_demo.png
  en/images/button_demo@2x.png
  en/images/button_disabled.png
  en/images/button_disabled@2x.png
  en/images/button_do1.png
  en/images/button_do1@2x.png
  en/images/button_do2.png
  en/images/button_do2@2x.png
  en/images/button_do3.png
  en/images/button_do3@2x.png
  en/images/button_dont1.png
  en/images/button_dont1@2x.png
  en/images/button_dont2.png
  en/images/button_dont2@2x.png
  en/images/button_dont3.png
  en/images/button_dont3@2x.png
  en/images/button_states.png
  en/images/button_states@2x.png
  en/images/button_templates.png
  en/images/button_templates@2x.png
  en/images/button_types.png
  en/images/button_types@2x.png
  en/images/pricing_plan.png
  en/images/pricing_plan@2x.png
  en/patterns/pricing-table.md
  en/sidebar-toc/toc.yml
  jp/images/button_demo.png
  jp/images/button_demo@2x.png
  jp/images/button_disabled.png
  jp/images/button_disabled@2x.png
  jp/images/button_do1.png
  jp/images/button_do1@2x.png
  jp/images/button_do2.png
  jp/images/button_do2@2x.png
  jp/images/button_do3.png
  jp/images/button_do3@2x.png
  jp/images/button_dont1.png
  jp/images/button_dont1@2x.png
  jp/images/button_dont2.png
  jp/images/button_dont2@2x.png
  jp/images/button_dont3.png
  jp/images/button_dont3@2x.png
  jp/images/button_states.png
  jp/images/button_states@2x.png
  jp/images/button_templates.png
  jp/images/button_templates@2x.png
  jp/images/button_types.png
  jp/images/button_types@2x.png
  jp/images/pricing_plan.png
  jp/images/pricing_plan@2x.png
  jp/patterns/pricing-table.md
  jp/sidebar-toc/toc.yml
Labels: status: verified, localization-pending

#630 [Localization] Adding the latest topic changes - JA.
  jp/components/badge.md
  jp/components/dropdown.md
  jp/components/navbar.md
  jp/components/time-picker.md
  jp/getting-started.md
Labels: localized
