Repository IgniteUI/indigo-design-docfx, pull requests merged in 2023-04, with the labels that each got.

#660 Add new topic figma swap
  en/how-to-swap-libraries.md
  en/images/how-to-swap-libraries/01.png
  en/images/how-to-swap-libraries/02.png
  en/images/how-to-swap-libraries/03.png
  en/images/how-to-swap-libraries/04.png
  en/images/how-to-swap-libraries/05.png
  en/images/how-to-swap-libraries/06.png
  en/images/how-to-swap-libraries/07.png
  en/sidebar-toc/toc.yml
  package-lock.json
  package.json
Labels: localization-pending

#659 Updating JP with the latest topic changes - new plugin topics, known issues, other updates.
  jp/best-layout-practices-figma.md
  jp/best-layout-practices-sketch.md
  jp/best-layout-practices-xd.md
  jp/best-layout-practices.md
  jp/codegen/layout-codegen.md
  jp/components/time-picker.md
  jp/docfx.json
  jp/images/create-from-common.png
  jp/images/create-from-figma.gif
  jp/images/dark-mode-variation.png
  jp/images/figma-auto-layout.png
  jp/images/figma-plugin.gif
  jp/images/figma_export_asset.PNG
  jp/images/figma_illustration_asset.PNG
  jp/images/figma_image_asset.PNG
  jp/images/xd-plugin.gif
  jp/known-issues.md
  jp/plugins/figma-plugin.md
  jp/plugins/overview-plugins.md
  jp/plugins/sketch-plugin.md
  jp/plugins/xd-plugin.md
  jp/quick-tips.md
  jp/sidebar-toc/toc.yml
  jp/style/colors.md
  jp/style/material-icons.md
  jp/sync-themes-plugin.md
Labels: status: verified, localized

#662 Replace environment variables
  gulpfile.js
Labels: status: verified

#664 Update template version
  en/quick-tips.md
  package-lock.json
  package.json
Labels: status: verified

#656 feat(*): updating docfx-template and builds
  .config/dotnet-tools.json
  .github/workflows/node.js.yml
  README.md
  en/docfx.json
  en/images/figma_export_asset.png
  en/images/figma_illustration_asset.png
  en/images/figma_image_asset.png
  en/images/indigo-design-ui-kit.png
  en/quick-tips.md
  gulpfile.js
  jp/docfx.json
  package-lock.json
  package.json
Labels: status: verified

#666 [JP] Adding the latest topic updates - new Figma topics, other changes.
  jp/codegen/layout-codegen.md
  jp/components/card-skeleton.md
  jp/components/column-chart.md
  jp/components/grid-skeleton.md
  jp/components/hierarchical-grid-skeleton.md
  jp/components/tree-grid-skeleton.md
  jp/creating-a-frame-in-figma.md
  jp/how-to-swap-libraries.md
  jp/images/figma-frame/getting-started-figma1.png
  jp/images/figma-frame/getting-started-figma10.png
  jp/images/figma-frame/getting-started-figma10@2x.png
  jp/images/figma-frame/getting-started-figma11.png
  jp/images/figma-frame/getting-started-figma11@2x.png
  jp/images/figma-frame/getting-started-figma12.png
  jp/images/figma-frame/getting-started-figma12@2x.png
  jp/images/figma-frame/getting-started-figma13.png
  jp/images/figma-frame/getting-started-figma13@2x.png
  jp/images/figma-frame/getting-started-figma14.png
  jp/images/figma-frame/getting-started-figma14@2x.png
  jp/images/figma-frame/getting-started-figma1@2x.png
  jp/images/figma-frame/getting-started-figma2.png
  jp/images/figma-frame/getting-started-figma2@2x.png
  jp/images/figma-frame/getting-started-figma3.png
  jp/images/figma-frame/getting-started-figma3@2x.png
  jp/images/figma-frame/getting-started-figma4.png
  jp/images/figma-frame/getting-started-figma4@2x.png
  jp/images/figma-frame/getting-started-figma5.png
  jp/images/figma-frame/getting-started-figma5@2x.png
  jp/images/figma-frame/getting-started-figma6.png
  jp/images/figma-frame/getting-started-figma6@2x.png
  jp/images/figma-frame/getting-started-figma7.png
  jp/images/figma-frame/getting-started-figma7@2x.png
  jp/images/figma-frame/getting-started-figma8.png
  jp/images/figma-frame/getting-started-figma8@2x.png
  jp/images/figma-frame/getting-started-figma9.png
  jp/images/figma-frame/getting-started-figma9@2x.png
  jp/images/how-to-swap-libraries/01.png
  jp/images/how-to-swap-libraries/02.png
  jp/images/how-to-swap-libraries/03.png
  jp/images/how-to-swap-libraries/04.png
  jp/images/how-to-swap-libraries/05.png
  jp/images/how-to-swap-libraries/06.png
  jp/images/how-to-swap-libraries/07.png
  jp/images/layout_codegen_ext_comps.png
  jp/known-issues.md
  jp/quick-tips.md
  jp/sidebar-toc/toc.yml
  jp/style/material-icons.md
Labels: status: verified, localized

#668 Added Retina Images and other fixes to the Creating a Frame in Figma page
  en/creating-a-frame-in-figma.md
  en/creating-artboard-adobexd.md
  en/creating-artboard-sketch.md
  en/images/figma-frame/getting-started-figma3.png
  en/images/figma-frame/getting-started-figma7.png
  en/images/figma-frame/getting-started-figma7@2x.png
  en/sidebar-toc/toc.yml
Labels: localization-pending

#670 [JP] Updating Figma topic, other changes.
  jp/creating-a-frame-in-figma.md
  jp/creating-artboard-adobexd.md
  jp/creating-artboard-sketch.md
  jp/images/figma-frame/getting-started-figma7.png
  jp/images/figma-frame/getting-started-figma7@2x.png
  jp/sidebar-toc/toc.yml
Labels: localized

#675 Update template version
  README.md
  package-lock.json
  package.json
Labels: status: awaiting-test

#692 Progress documentation refinement
  en/components/progress.md
  en/images/progress_circular.png
  en/images/progress_circular@2x.png
  en/images/progress_circular_determinate.png
  en/images/progress_circular_determinate@2x.png
  en/images/progress_circular_indeterminate.png
  en/images/progress_circular_indeterminate@2x.png
  en/images/progress_linear.png
  en/images/progress_linear@2x.png
  en/images/progress_linear_determinate.png
  en/images/progress_linear_determinate@2x.png
  en/images/progress_linear_indeterminate.png
  en/images/progress_linear_indeterminate@2x.png
Labels: localization-pending

#694 Added info about the usage of Slider in Figma
  en/components/slider.md
  en/images/slider_demo.png
  en/images/slider_demo@2x.png
  en/images/slider_disabled.png
  en/images/slider_disabled@2x.png
  en/images/slider_do1.png
  en/images/slider_do1@2x.png
  en/images/slider_do2.png
  en/images/slider_do2@2x.png
  en/images/slider_dont1.png
  en/images/slider_dont1@2x.png
  en/images/slider_dont2.png
  en/images/slider_dont2@2x.png
  en/images/slider_enabled.png
  en/images/slider_enabled@2x.png
  en/images/slider_onethumb.png
  en/images/slider_onethumb@2x.png
  en/images/slider_styling.png
  en/images/slider_styling@2x.png
Labels: localization-pending

#714 Added info for the usage of the Chart components in Figma
  en/components/column-chart.md
  en/components/line-chart.md
  en/components/pie-chart.md
  en/components/skeleton-charts.md
  en/components/spline-chart.md
  en/components/step-line-chart.md
  en/images/pie_chart_demo.png
  en/images/pie_chart_demo@2x.png
  en/images/pie_chart_do.png
  en/images/pie_chart_do@2x.png
  en/images/pie_chart_dont.png
  en/images/pie_chart_dont@2x.png
  en/images/pie_chart_labels_center.png
  en/images/pie_chart_labels_center@2x.png
  en/images/pie_chart_labels_insideend.png
  en/images/pie_chart_labels_insideend@2x.png
  en/images/pie_chart_labels_outsideend.png
  en/images/pie_chart_labels_outsideend@2x.png
  en/images/pie_chart_series3.png
  en/images/pie_chart_series3@2x.png
  en/images/pie_chart_series4.png
  en/images/pie_chart_series4@2x.png
  en/images/pie_chart_series5.png
  en/images/pie_chart_series5@2x.png
  en/images/pie_chart_styling.png
  en/images/pie_chart_styling@2x.png
  en/images/skeleton_charts_pie.png
  en/images/skeleton_charts_pie@2x.png
  en/sidebar-toc/toc.yml
Labels: localization-pending

#695 Added info for the usage of the Time Picker in Figma
  en/components/time-picker.md
  en/images/timepicker_demo.png
  en/images/timepicker_demo@2x.png
  en/images/timepicker_disabled.png
  en/images/timepicker_disabled@2x.png
  en/images/timepicker_do2.png
  en/images/timepicker_do2@2x.png
  en/images/timepicker_dont2.png
  en/images/timepicker_dont2@2x.png
  en/images/timepicker_enabled.png
  en/images/timepicker_enabled@2x.png
Labels: localization-pending
